### ISSUE TITLE
Consider single file output

### ISSUE THREAD

**Issue by guybedford** [aaronfrost/grunt-traceur#21]
As discussed in https://github.com/aaronfrost/grunt-traceur/issues/20, it can be useful to compile all the files into one.

For Traceur, it provides this through:

``` javascript
  var compileFile = require('traceur/src/node/compile-single-file');
  var traceur = require('traceur');
  traceur.options.modules = 'inline';
  compileFile('input.js', 'output.js');
```

The above would compile `input.js` **and all of its dependencies** into a single output file that would work with traceur runtime present.

May be a useful alternative option for users not wanting to do a separate build process.

Also if you are interested in these workflows, do see my article! http://guybedford.com/practical-workflows-for-es6-modules

**Comment by sindresorhus** [comment]
Traceur ticket: https://github.com/google/traceur-compiler/issues/1626
