### ISSUE TITLE
Add some mention about traceur runtime in the doc as it is necessary to work

### ISSUE THREAD

**Issue by HadrienPierart** [aaronfrost/grunt-traceur#52]
I got stuck for 30min on this and had to dig aroung in the issue of traceur to figure that you had to add the runtime for this whole thing to work.
Otherwise, here is what you get (depending on if you set `moduleNames: true` in the options, as it it the default): 

    Uncaught ReferenceError: $traceurRuntime is not defined    app/scripts/es6/controllers/main.js:1 
    Uncaught ReferenceError: $traceurRuntime is not defined    app/scripts/es6/router.js:1 
    Uncaught ReferenceError: $traceurRuntime is not defined    app/scripts/es6/services/Authentication.js:1 
    Uncaught ReferenceError: $traceurRuntime is not defined    app/scripts/es6/services/Messages.js:1 
    Uncaught ReferenceError: $traceurRuntime is not defined    app/scripts/es6/app-mock.js:1 
    Uncaught ReferenceError: $traceurRuntime is not defined    angular.js:63 
    Uncaught Error: [$injector:modulerr] Failed to instantiate module MyModule due to...

You might also get this (depending on if you set `moduleNames: false` in the options) : 

    Uncaught ReferenceError: System is not defined

I had to copy traceur-runtime.js from your node_modules into my project and add it to my index.html like that :
`<script src="scripts/traceur-runtime/traceur-runtime.js"></script>`

I did see that you could pass the option `includeRuntime: true` in the grunt task and tried it but this adds the runtime to every file which is not suitable for a dev environment where you have multiple small files as the runtime gets prepended to each of them.

Would you mind adding a note about this in your readme or include the runtime as a default ?

**Comment by mciparelli** [comment]
Thanks, fixed here https://github.com/aaronfrost/grunt-traceur/commit/0588c1010509b743a8771a0442956e6e22f88a24
