### ISSUE TITLE
includeRuntime prepends only to the first file

### ISSUE THREAD

**Issue by aaronfrost** [aaronfrost/grunt-traceur#54]
Does it makes sense to modify the `includeRuntime` flag to only include the runtime in the first file? It would make life easier for everyone who uses grunt-traceur on a project. 

Currently, users have two options. 
1. Add the runtime to each file (not a good idea). 
2. Don't include the runtime (which means that they have to go get a copy on their own, ie: extra steps). 

It feels like we could make this easier for everyone by making the `includeRuntime` solve this problem for them. My question is... how do we solve it for them? Do we simply add the runtime to the first file only? Do we simply copy the runtime from the node_modules folder and copy it to the root of the destination?

How can we make this better for people?

**Comment by mciparelli** [comment]
Adding the runtime to the first file only would confuse node users don't you think? Renaming our config to `copyRuntime` which would be a Boolean indicating _whether we should perform a copy of this file into the root of the destination or not_ sounds much better to me.

**Comment by aaronfrost** [comment]
I agree. That make a lot of sense. Nothing unexpected, and we can still save them all of the steps. I will work on this tonight.

**Comment by aaronfrost** [comment]
So... the build is busted at work. I have time to look at this. Should we re-name and re-purpose the `includeRuntime` flag? Or should we create a second tag?

If we rename it, we are breaking users that depend on it. However, we could still look for it and log out that it is deprecated in place of `copyRuntime`. 

If we leave `includeRuntime` and add `copyRuntime`, I think that we will confuse people and I don't want to do that. Nor do I want to support the functionality of both of them. 

So, I say that we rename it to `copyRuntime`, breaking people that use `includeRuntime`, still watching for `includeRuntime` to warn about it, and `copyRuntime` copies the *traceur_runtime.js* from the `node_modules/traceur` directory and into the destination. Agreed? Suggestions?

**Comment by mciparelli** [comment]
Yeap, I agree, let's do it as you say. Maybe we could throw an error for
users that want to make use of `includeRuntime` indicating that they should
move to `copyRuntime` config. And I agree on the fact that keeping both is
confusing, lets just rename it.

**Comment by aaronfrost** [comment]
Update: `copyRuntime` is not a boolean. It is a directory where you want the runtime copied to. If copyRuntime is defined, we copy the runtime to the right dir. Thoughts?

**Comment by mciparelli** [comment]
Sure! Sounds even better

**Comment by aaronfrost** [comment]
I just PRd the solution. Let me know what you think.

**Comment by mciparelli** [comment]
Nicely done. https://github.com/aaronfrost/grunt-traceur/pull/55 closes this
