### ISSUE TITLE
Loading filerev-ed (fingerprinted) files

### ISSUE THREAD

**Issue by finishingmove** [aaronfrost/grunt-traceur#56]
Attempting something like

`<script>
  System.import('scripts/app').then(...);
</script>`

fails in production because the file is actually something like `scripts/app.b95s52.js`.

Is there a workaround for this?

**Comment by finishingmove** [comment]
Hm, I figured I can refer to them by the namespace created using the `moduleNaming.stripPrefix`, `moduleNaming.addPrefix' options. So, doing

`<script> System.import('com/example/app').then(...); </script>`

works in production, but then it breaks development.

I'm trying to integrate the `traceur` task into the `serve` and `watch` tasks. That seems like the way to go. Advice is welcome though ;)

**Comment by finishingmove** [comment]
Hm, I figured the solution was referring to it by the namespaced module name created using the `moduleNaming.stripPrefix`, `moduleNaming.addPrefix` options, in combination with the `System.config.paths` setting.

    <script>  
        System.config({  
            paths: {  
              'com/example/application/*': 'scripts/*.js'  
            }  
         });  
        System.import('com/example/application/app').then(...);  
    </script>

Now, the last piece of the puzzle: I'm getting warnings in development (`Unexpected reserved word`). The `export` and `import` keywords are causing them, though the app surprisingly runs fine.

I'm including the following in both development and production

`traceur.js`
`traceur-runtime.js`
`es6-module-loader.js`
`system.js`

and I am using the `traceur` grunt task only as part of `build`. Any advice on how to structure the development workflow to avoid the above-mentioned exceptions? Sorry that this went a bit out of scope, but I would really appreciate some insight! ;)

Thanks!

**Comment by mciparelli** [comment]
You want advice to avoid what exceptions *exactly*?

**Comment by finishingmove** [comment]
So, when I run the development server, the ES6 files are transpiled on the fly as I understand it. I include the 4 files mentioned above, and everything seems to work, but I get an exception logged in the console for every non-ES5 syntax in the code. For example, every line containing the `import` or `export` keywords will throw

    Uncaught SyntaxError: Unexpected reserved word

**Comment by mciparelli** [comment]
Well if you get that error in your code after loading traceur and traceur-runtime manually then you're probably writing something wrong. Your error sounds like it found an import or export where it shouldn't be. Hard to guess without looking at the code, but still if you're not using this plugin at all and you're loading traceur directly you will probably find better help in the traceur repo rather than here.
