### ISSUE TITLE
addPrefix not working with traceur 0.0.87

### ISSUE THREAD

**Issue by Avien** [aaronfrost/grunt-traceur#63]
Worked for me on 0.0.81, stopped working after updating traceur to 0.0.87

**Comment by mciparelli** [comment]
What options are you using? It works for me using these from the project `Gruntfile.js`:
```javascript
      options: {
        experimental: true,
        modules: 'register',
        sourceMaps: true,
        arrayComprehension: true,
        generatorComprehension: true,
        moduleNaming: {
          stripPrefix: "test/tmp",
          addPrefix: "test/fixtures"
        },
        copyRuntime: "test/tmp"
        // traceur options here
      },
```

**Comment by Avien** [comment]
I don't know what this is: 
```javascript
        arrayComprehension: true,
        generatorComprehension: true
```
(any documantion for it?)

However I did try:
```javascript
moduleNaming: {
          stripPrefix: "test/tmp",
          addPrefix: "test/fixtures"
        }
```
But neither is working

**Comment by mciparelli** [comment]
Where are you trying it? If there's a repo you can link me to I could clone it and check why it's not working for you.

**Comment by mciparelli** [comment]
Those two are just Traceur options to enable generators and array comprehensions: https://github.com/google/traceur-compiler/wiki/LanguageFeatures#array-comprehension-experimental

**Comment by Avien** [comment]
It's all because of the breaking changes made to the latest version of traceur in which the .js extension is omitted which forces me to refactor my grunt tasks, hence the addPrefix needs to be changed but not working for me...
I just sticked to version 0.0.8.1 for now, cant waste another time on it
thanks

**Comment by mciparelli** [comment]
Ok, if you ever want to dig in and see why it's not working for you with latest version, please reopen.

**Comment by Avien** [comment]
Thanks!
