### ISSUE TITLE
addPrefix broken node traceur 0.0.88

### ISSUE THREAD

**Issue by gso** [aaronfrost/grunt-traceur#64]
This was opened and closed, if I can add it back - https://github.com/aaronfrost/grunt-traceur/issues/63

node traceur 0.0.81 adds the module name prefix fine, however upgrading to 0.0.88 leaves the directory from which traceur is run as the module name prefix.

Config. file:

    grunt.initConfig({
        traceur: {
            options: {
                // traceur options here
                experimental: true,
                modules: 'register',
                // module naming options,
                moduleNaming: {
                    stripPrefix: "out/sr",
                    addPrefix: "gso/eonjs"
                },
                copyRuntime: 'lib'
            },
            custom: {
                files: [{
                    expand: true,
                    cwd: 'src',
                    src: ['*.js'],
                    dest: 'out/sr'
                }]
            }
        }
    });

Output with node traceur 0.0.88:

    System.registerModule("src/AbstractRecurRule.js", [], function() {
      "use strict";
      var __moduleName = "src/AbstractRecurRule.js";

Intended output with node traceur 0.0.81:

    System.registerModule("gso/eonjs/AbstractRecurRule", [], function() {
       "use strict";
       var __moduleName = "gso/eonjs/AbstractRecurRule";

**Comment by mciparelli** [comment]
Oh crap, you guys are right. I didn't notice because I had my `moduleNaming` configured to match the source, which apparently is the new path traceur outputs as part of the module name and it doesn't look at `options.moduleName` anymore. I'll investigate it a little and get back to you. Sorry for the confusion.

**Comment by mciparelli** [comment]
Looks like the `moduleName` option changed entirely: https://github.com/google/traceur-compiler/commit/9d88d8929309064b10db24a630419704eb45691f

**Comment by gso** [comment]
Same result also with the `stripPrefix` set tp `src` also:

    moduleNaming: {
        //stripPrefix: "out/sr",
        stripPrefix: "src",
        addPrefix: "gso/eonjs"
    },

**Comment by mciparelli** [comment]
Fixed at c47665f

**Comment by gso** [comment]
The stripPrefix has to be changed to the src dir, otherwise working again, cheers.

**Comment by mciparelli** [comment]
Ah, right. That breaks backwards compatibility, so I guess I'll make it default to the dest dir and release again.
