### ISSUE TITLE
Prefix stripping doesn't work on windows

### ISSUE THREAD

**Issue by Strilanc** [aaronfrost/grunt-traceur#66]
The code

    if (stripPrefix) {
            var namePrefixMatched = (stripPrefix + path.sep) ===
              options.sourceName.substring(0, stripPrefix.length + path.sep.length);

Doesn't work correctly on windows, because path.sep only matches \ instead of matching / or \.

I think it would be better to just unconditionally use "/" in this case, or to avoid specifying the separator entirely.

**Comment by Strilanc** [comment]
?

**Comment by ivan-ravecca** [comment]
I can confirm this is not working on windows, and the workaround was adding that override.

**Comment by spinningarrow** [comment]
+1

**Comment by Strilanc** [comment]
https://github.com/aaronfrost/grunt-traceur/pull/68 fixed this and is now merged.
