### ISSUE TITLE
Update grunt dep to >=0.4.0

### ISSUE THREAD

**Issue by Strilanc** [aaronfrost/grunt-traceur#70]
[Grunt 1.0.0 has been released](http://gruntjs.com/blog/2016-04-04-grunt-1.0.0-released). I can't use it at the same time as grunt-traceur because grunt-traceur asks for 0.4.

**Comment by aaronfrost** [comment]
@Strilanc I will approve a PR if you got one.

**Comment by aaronfrost** [comment]
Nevermind. I accepted the PR. Sorry for taking so long.

**Comment by Strilanc** [comment]
Fixed by https://github.com/aaronfrost/grunt-traceur/pull/69
